dist: trusty
sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial
      - libffi-dev
      - libsdl2-dev
      - gcc-4.8-plugin-dev

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  # Prepare directory for the toolchain
  git submodule update --init --recursive

script:
  - pip install pyserial
  # Update configuration so that kconfig doesn't start interactive mode
  - make --version
  - du -hs
  - source set_env.sh
  - make defconfig
  # Build project from the git repository
  - make -j3
  # Build the micropython firmware
  - make -j3 -C micropython/esp32
  # Build micropython unix 'badge emulator'
  - git clone https://github.com/ARMmbed/mbedtls.git micropython/lib/mbedtls
  - make -j3 -C micropython/lib/mbedtls
  - make -j3 -C micropython/unix
  - du -hs

notifications:
  irc:
    channels:
      - "chat.freenode.net#sha2017-badge"
      - "chat.freenode.net#sha2017-badge-dev"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
